#!/bin/bash
qsub -wd /export/a06/sheng/ job_script_0.sh
qsub -wd /export/a06/sheng/ job_script_1.sh
qsub -wd /export/a06/sheng/ job_script_2.sh
qsub -wd /export/a06/sheng/ job_script_3.sh
qsub -wd /export/a06/sheng/ job_script_4.sh
qsub -wd /export/a06/sheng/ job_script_5.sh
qsub -wd /export/a06/sheng/ job_script_6.sh
qsub -wd /export/a06/sheng/ job_script_7.sh
qsub -wd /export/a06/sheng/ job_script_8.sh
qsub -wd /export/a06/sheng/ job_script_9.sh
qsub -wd /export/a06/sheng/ job_script_10.sh
qsub -wd /export/a06/sheng/ job_script_11.sh
qsub -wd /export/a06/sheng/ job_script_12.sh
qsub -wd /export/a06/sheng/ job_script_13.sh
qsub -wd /export/a06/sheng/ job_script_14.sh
qsub -wd /export/a06/sheng/ job_script_15.sh
qsub -wd /export/a06/sheng/ job_script_16.sh
qsub -wd /export/a06/sheng/ job_script_17.sh
qsub -wd /export/a06/sheng/ job_script_18.sh
qsub -wd /export/a06/sheng/ job_script_19.sh
